#ifndef INDEX_NOTATION_H
#define INDEX_NOTATION_H

enum COMMAND {
    NO_ACT = 0,
    TEST,
    CUSTOM_COMMAND,
    SPEED_COMMAND,
    ENABLE_COMMAND,
    OFF_COMMAND,
    STOP_COMMAND,
    TORQUE_COMMAND,
    MULTI_TURN_POS_CL_COMMAND,
    SINGLE_TURN_POS_CL_COMMAND,
    MULTI_MOTOR_TORQUE_COMMAND,
            
    HOMING,    
    ORIGINPOINT_COMMAND,
};

#endif // INDEX_NOTATION_H
